
project:
  type: website
  output-dir: _site

website:
  title: "Oregon Enterprise Data Analytics"
  navbar:
    logo: /assets/oeda-icon-lighter.svg
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: oeda_brand.qmd
        text: Branding Intro
      - href: issues.qmd
        text: Issues and Bugs

theme:
  light: [flatly, theme.scss] 
  dark: [darkly, theme-dark.scss]

format:
  html:
    toc: true
    code-fold: true

# Simple knitr setup - no special devices needed!
knitr:
  opts_chunk:
    echo: false
    warning: false 
    message: false
    dev: "svglite"