
project:
  type: website
  output-dir: _site

    
website:
  title: "Oregon Enterprise Data Analytics"
  site-url: "https://dhs-oeda.github.io/"
  repo-url: "https://github.com/DHS-OEDA/oeda_branding"
  navbar:
    logo: /assets/oeda-icon-light-header.png
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: oeda_brand.qmd
        text: Branding
      - href: issues.qmd
        text: Issues and Bugs
      - icon: github
        href: https://github.com/DHS-OEDA/oeda_branding
  sidebar:
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Website"
        contents:
          - href: oeda_brand.qmd
            text: Brand Demo
          - href: buttons.qmd
            text: Buttons
          - href: cards.qmd
            text: Cards
      - href: issues.qmd
        text: Issues and Bugs
    

theme:
  light: [flatly, theme.scss] 
  dark: [darkly, theme-dark.scss]

format:
  html:
    toc: true
    toc-depth: 2
    toc-title: Contents
    toc-location: right
    code-fold: true

# Simple knitr setup - no special devices needed!
knitr:
  opts_chunk:
    echo: false
    warning: false 
    message: false
    dev: "svglite"