
project:
  type: website
  output-dir: _site

    
website:
  title: "Oregon Enterprise Data Analytics"
  site-url: "https://dhs-oeda.github.io/"
  repo-url: "https://github.com/DHS-OEDA/oeda_branding"
  repo-actions: [source, issue]
  reader-mode: true
  page-footer:
    left: "Oregon Enterprise Data Analytics, 2025"
    right:
      - icon: github
        href: https://github.com/DHS-OEDA/oeda_branding
  navbar:
    logo: /assets/oeda-icon-light-header.png
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: oeda_brand.qmd
        text: Branding
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/DHS-OEDA/oeda_branding
          - text: Report a Bug
            href: https://github.com/DHS-OEDA/oeda_branding/issues/new

  sidebar:
    search: true
    background: none
    contents:
      - href: index.qmd
        text: Home
      - section: "Website"
        contents:
          - href: oeda_brand.qmd
            text: Light and Dark Mode
          - href: buttons.qmd
            text: Buttons
      - section: "Dashboard"
      - href: issues.qmd
        text: Issues and Bugs

theme:
  light: [flatly, theme.scss] 
  dark: [darkly, theme-dark.scss]

format:
  html:
    toc: true
    toc-depth: 2
    toc-title: Contents
    toc-location: right
    code-fold: true
dashboard:
  theme:
    light: [flatly, theme.scss] 
    dark: [darkly, theme-dark.scss]
  logo: /assets/oeda-icon-light-header.png
    # You can also set dashboard-specific navigation
  nav-buttons:
    - icon: github
      href: https://github.com/DHS-OEDA/oeda_branding  

# Simple knitr setup - no special devices needed!
knitr:
  opts_chunk:
    echo: false
    warning: false 
    message: false
    dev: "svglite"