project:
  type: website
  output-dir: _site

website:
  title: "Oregon Enterprise Data Analytics"
  navbar:
    left:
      - href: index.qmd # Or whatever your main page is
        text: Home
      - href: oeda_brand.qmd 
        text: Web Branding
      - href: issues.qmd
        text: Issues and Bugs
      - href: brand-pdf.qmd
        text: PDF Branding
logo:
  light: /assets/oeda-icon-lighter.svg
  dark: /assets/oeda-icon-dark.svg
  alt: "OEDA Logo"

# Keep the theme at the top level (unindented).
theme:
  light: [flatly, theme.scss]
  dark: [darkly, theme-dark.scss]

format:
  html:
    toc: true
    toc-float: true
    code-copy: true
    code-fold: true
    code-summary: "Show the code"
